# Generated by Django 2.2.4 on 2026-09-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20260929_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='ACCESORIES MA', max_length=100)),
                ('announcement_text', models.CharField(default='LIVRAISON GRATUITE À PARTIR DE 370 DH', max_length=180)),
                ('shipping_fee', models.FloatField(default=35)),
                ('free_shipping_threshold', models.FloatField(default=370)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Paramètres de la boutique',
                'verbose_name_plural': 'Paramètres de la boutique',
            },
        ),
    ]
