# Generated by Django 2.2.4 on 2026-09-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_storesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='storesettings',
            name='cities',
            field=models.TextField(default='Casablanca\nRabat\nSalé\nMarrakech\nFès\nTanger\nAgadir\nMeknès\nOujda\nKénitra\nTétouan\nSafi\nEl Jadida\nBéni Mellal\nNador\nKhouribga\nSettat\nLaâyoune\nDakhla'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='store/'),
        ),
    ]
