# Generated by Django 2.2.4 on 2026-09-29 23:29

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(help_text='Size: 1920x570', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='store/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size]),
        ),
    ]
